### ISSUE TITLE
GitHub Actions without installing the app

### ISSUE THREAD

**Issue by kmh4321** [kentaro-m/auto-assign#103]
**Describe the bug**
Hello, 
I was trying to enable this using GitHub actions. Would it be possible to do that without installing the app?

**To Reproduce**
1. Create `main.workflow` and `yml` file as instructed.
2. Try opening a Pull request.

**Expected behavior**
PR should be assigned to user in the `yml` file.

**Screenshots**
test repo: https://github.com/bdwyer2/gh_actions

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 68.0.2

**Comment by kentaro-m** [comment]
Hi, @kmh4321.
Thank you for your interest in the auto-assign app.
This app is not working for GitHub Action v2.

Related issue: https://github.com/probot/probot/issues/1028

Currently, I'm developing the auto-assign action to support for GitHub Action v2.
If you are interested, please check this out.

https://github.com/kentaro-m/auto-assign-action

**Comment by kmh4321** [comment]
@kentaro-m Thank you for the update! 
I have tried it out and it seems to work now. 
Any idea how I can expand it to auto assign issues as well?
