### ISSUE TITLE
missing "numberOfReviewers" key should add all reviewers

### ISSUE THREAD

**Issue by eltonlauhk01** [kentaro-m/auto-assign#107]
**Describe the bug**
missing "numberOfReviewers" in auto_assign.yml should add all reviewers

**To Reproduce**
1. have .github/auto_assign.yml with no "numberOfReviewers" key, in default branch
2. create pull request

**Expected behavior**
missing "numberOfReviewers" in auto_assign.yml should add all reviewers
according to README, default: 0

**Additional context**
https://github.com/kentaro-m/auto-assign/blob/43fa337a4fbee2a5866779cffa418b1d6f33d118/src/util.ts#L15
`  if (desiredNumber === 0) {`
should be
`  if (!desiredNumber || desiredNumber === 0) {`

https://github.com/kentaro-m/auto-assign/blob/43fa337a4fbee2a5866779cffa418b1d6f33d118/src/auto_assign.ts#L42

**Comment by spaceemotion** [comment]
We're observing the same problem, is there a way to fix this despite the wontfix tag?
