### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by kentaro-m** [kentaro-m/auto-assign#31]
**Describe the bug**

This error is thrown when auto-assign do not have permission to use the API. auto-assign uses `getContents` API to get `.github/auto_assign.yml`.

I have confirmed that this error has occurred in the private repository. It seems that auto-assign can access the configuration file, even if you do not have permissions in the public repository.

Previously, auto-assign did not have the permission to use `getContents` API. I was pointed out it from the user, added the permission.

**To Reproduce**
Users who have been using this application before changing permissions need to reinstall auto-assign.

**Expected behavior**
auto-assign can read the configuration file.

**Screenshots**
I added the permission after the user pointed out.
<img width="767" alt="screen shot 2018-10-08 at 20 14 34" src="https://user-images.githubusercontent.com/7448569/46606170-d9599780-cb36-11e8-8e8d-8fabe2085c79.png">

**Comment by colindean** [comment]
@kentaro-m Can you explain what `Error: Resource not accessible by integration` means? You've not provided more than that…

**Comment by kentaro-m** [comment]
@colindean 
I added detailed information to the description of PR.

**Comment by kentaro-m** [comment]
@colindean @davetcoleman 
I have investigated this issue. Would you please try the solution below.

**Solution**
I added a new permission for running auto-assign on 18th October. Newly added is to call `getContents` API which is used to read `auto_assign.yml`.

(Previously, I added the `Single file` permission, but it seems it was not enough)

Please follow the procedure below to enable this setting.

1. Please confirm the email which the subject indicates "[GitHub] A GitHub App, auto-assign, is requesting updated permissions". It should have been sent on 18th October.
2. Click a link that included "permission/update" in the mail.
3. Click a button "Accept new permissions"

<img width="1278" alt="screen shot 2018-10-21 at 19 28 15" src="https://user-images.githubusercontent.com/7448569/47265741-9a303b00-d567-11e8-8eb4-a0e9cd7760d3.png">

**Comment by colindean** [comment]
I did receive the email and did act on it. I’ve not tested with more than one repo that had already been intermittently working. I’ll observe some more this week.

**Comment by davetcoleman** [comment]
I clicked the confirm button but, after creating another PR, people were still not assigned...

**Comment by colindean** [comment]
I am no longer a part of the organization where I was primarily using auto-assign, but, to my recollection,  we had not had any problems related to this issue.
