### ISSUE TITLE
Team not being set as a reviewer

### ISSUE THREAD

**Issue by colindean** [kentaro-m/auto-assign#39]
**Describe the bug**

I've listed a team in the reviews as `org/team-name` and it does not appear to be added as a reviewer.

**To Reproduce**

1. Include a team in the `reviewers` list

**Expected behavior**

I expect the team to be added as a reviewer.

**Comment by colindean** [comment]
I still want to do this and might have time this week to implement it.

**Comment by tobiaskohlbau** [comment]
We would like to see this feature within `auto-assign`.
Would you be willing on reopening this issue?

**Comment by mrlubos** [comment]
Hi everyone! I found your thinking very useful @colindean and I created a pull request adding this functionality in #120. I would appreciate your feedback!
