### ISSUE TITLE
Is this hosted?

### ISSUE THREAD

**Issue by allanchau** [kentaro-m/auto-assign#47]
**Describe the bug**
I installed the app, but nobody is being assigned.

**Expected behavior**
Users are assigned to PRs.

**Additional context**
I wasn't sure if it needed to be deployed manually or this is a hosted app.

**Comment by allanchau** [comment]
Just a thought, I am trying to use the app on a private repo.
Does this app require updated permissions to make it work?

**Comment by kentaro-m** [comment]
@allanchau 
> Does this app require updated permissions to make it work?

Yes, it does. Probably I think that [this solution](https://github.com/kentaro-m/auto-assign/issues/31#issuecomment-431661966) will solve it.

**Comment by allanchau** [comment]
@kentaro-m I did try that, but it still isn't assigning 😢.
Do you need to add @ to the name `@allanchau`? or will `allanchau` etc work?
