### ISSUE TITLE
Ability to exclude pull request opener from asignees/reviewers

### ISSUE THREAD

**Issue by keirlawson** [kentaro-m/auto-assign#75]
**Is your feature request related to a problem? Please describe.**
Presently whilst the owner of the repository is excluded from the possible assignees/reviewers, the person who opened the pull request is not.

**Describe the solution you'd like**
An option to exclude the opener of the pull request.

**Comment by JimNero009** [comment]
This seems like quite a fundamental feature, so could we remove the wontfix label please?

**Comment by JimNero009** [comment]
Thanks bot :D

**Comment by JimNero009** [comment]
Was just about to look at adding this, but seems as if this functionality is now present -- could you confirm?
For example, I see that an 'owner' param is passed down to the chooseUsers and chooseUsersFromGroups utilities, and that 'owner' param has the value of the username of the user that opened the pull request - https://github.com/kentaro-m/auto-assign/blob/master/src/auto_assign.ts#L30. The logic in the utility functions seem to filter out this owner when returning the list of choices. Could you confirm this is correct? If so, this issue can be closed.

**Comment by kentaro-m** [comment]
@JimNero009 
Thanks for your questions. The issue that pull request owner cannot exclude from the reviewer have been fixed in PR https://github.com/kentaro-m/auto-assign/pull/72.

**Comment by JimNero009** [comment]
Smashing. Happy to close!
