### ISSUE TITLE
Can this be installed and used on a Github Enterprise server?

### ISSUE THREAD

**Issue by dehrenheim** [kentaro-m/auto-assign#86]
Just wondering if 
a) can this be installed on Github Enterprise and 
b) if you plan to provide documentation to possibly clone and run on a GHE server?

We are currently on version 2.16.6 of GHE.

Please let me know if this is the incorrect method to ask such a question.

Thanks.

**Comment by kentaro-m** [comment]
Hi, @dehrenheim.
This app can be installed on GitHub Enterprise by adding `GHE_HOST` to `.env` file. 

```
GHE_HOST=example.githubenterprise.com
```

`GHE_HOST` description is written on the Probot official document ([Environment configuration | Probot](https://probot.github.io/docs/configuration/)).

> The hostname of your GitHub Enterprise instance.

I have no plans to provide documentation for this content, as it is listed in the official documentation. But improving document is always welcome. Let me know if you have any questions.

**Comment by dehrenheim** [comment]
Thank you for the reply. This helps tremendously.
